### ISSUE TITLE
NUL-supported VIPS lambda layer is timing out on images with large pixel dimensions ( ~15,000 pixels )

### ISSUE THREAD

**Issue by bmquinn** [samvera/serverless-iiif#101]
### Description
It looks like this change to the template added a lambda layer version that is failing to deliver images in time:
https://github.com/samvera/serverless-iiif/blob/f4fdaadfc9f4e4cfb525e9ba6cff5f7e0b2e893b/sam/standalone/template.yml#L123

In our application, we reverted to `version 1` of the lambda layer and it got large images to work again.

**Comment by davidschober** [comment]
@mbklein did this get sorted in the other work you did on serverless iiif?

**Comment by davidschober** [comment]
The issue itself is sorted. This the work for the layer itself.

**Comment by mbklein** [comment]
This issue is going to depend on how lovell/sharp#3750 plays out. Closing this issue and will open a new one if necessary.
