### ISSUE TITLE
Look into Lambda Streaming Response to replace 6MB workaround

### ISSUE THREAD

**Issue by mbklein** [samvera/serverless-iiif#109]
AWS Lambda now supports [streaming-enabled functions](https://docs.aws.amazon.com/lambda/latest/dg/configuration-response-streaming.html), with a soft response payload size limit of 20MB, instead of the hard 6MB limit on buffered responses. This might be an opportunity to simplify our deployment by getting rid of the need for the cache bucket/CloudFront failover origin workaround for large responses.

**Comment by codeclout** [comment]
@mbklein - We have implemented the streaming response by creating a Readable stream from the result of `resource.execute()` 

e.g. 

```
const result = await resource.execute();
  streamResponse.setContentType(result.contentType);
  const r = Readable.from(result.body);

  await pipeline(r, streamResponse);
```

We have confirmed it works as expected. Would you be interested in a pull request?

**Comment by mbklein** [comment]
Sure!

**Comment by codeclout** [comment]
@mbklein - quick update

The PR was written on GFE, so therefore I need some approvals and I am working internally to retain the necessary approvals.
