### ISSUE TITLE
unable to deploy standalone version

### ISSUE THREAD

**Issue by t4k** [samvera/serverless-iiif#115]
I've deployed this application a number of times from my user account, including the current version, successfully.

The only customization besides providing a unique name a source bucket is to change the ResolverTemplate setting from `%s.tif` to `%s.ptif` which has always worked before.

The following is a redacted version of the message I see in the CloudFormation Stack CREATE_FAILED status.

> Resource handler returned message: "User: arn:aws:iam::000000000000:user/xxx is not authorized to perform: lambda:GetLayerVersion on resource: arn:aws:lambda:us-west-2:000000000000:layer:libvips-sharp-jp2:3 because no resource-based policy allows the lambda:GetLayerVersion action (Service: Lambda, Status Code: 403, Request ID: -uuid-)" (RequestToken: -uuid-, HandlerErrorCode: AccessDenied)

**Comment by mbklein** [comment]
Ah, sorry about that. The most recent deployment of the layer must not have set the permissions correctly. I’m not at a computer where I can fix it right this minute, but I can take care of it within a few hours.

**Comment by t4k** [comment]
No worries! Thanks for the prompt response. I'm at the end of my work day so I won't be looking at this again for another 16 hours or so.

**Comment by mbklein** [comment]
Should be good to go now.
