### ISSUE TITLE
Error: Input buffer has corrupt header: tiff2vips: TIFF does not contain page 6

### ISSUE THREAD

**Issue by fitnycdigitalinitiatives** [samvera/serverless-iiif#154]
Hello,

I've been getting this error with some images, though, only for certain requests within the image itself:
`Error: Input buffer has corrupt header: tiff2vips: TIFF does not contain page 6`
For instance, this request `https://d2zekfy08kmwea.cloudfront.net/iiif/3/packages/9ba5/7175/5aee/4b3b/a49b/0eee/eac8/54e9/mi_000003-72cb2176-37cb-47cc-acb9-fedf533bdab6/objects/2471f2c4-a2f6-462a-bee0-9d054d0c74b4-20230620_3-_I2A2882/full/86,128/0/default.jpg` triggers the errors, though requests for other regions of the same image do not trigger it. The full size request works `https://d2zekfy08kmwea.cloudfront.net/iiif/3/packages/9ba5/7175/5aee/4b3b/a49b/0eee/eac8/54e9/mi_000003-72cb2176-37cb-47cc-acb9-fedf533bdab6/objects/2471f2c4-a2f6-462a-bee0-9d054d0c74b4-20230620_3-_I2A2882/full/max/0/default.jpg` and a smaller does too `https://d2zekfy08kmwea.cloudfront.net/iiif/3/packages/9ba5/7175/5aee/4b3b/a49b/0eee/eac8/54e9/mi_000003-72cb2176-37cb-47cc-acb9-fedf533bdab6/objects/2471f2c4-a2f6-462a-bee0-9d054d0c74b4-20230620_3-_I2A2882/full/342,512/0/default.jpg`

I'm not sure what's happening that it's looking for page 6. I can direct message you the source image, which is just a basic pyramid tiff generated the same way we do for all our images.

Thanks,

Joe

**Comment by mbklein** [comment]
What does your S3 object metadata for this image look like? Do you use a custom dimension resolution function?

When I run it locally, letting it read the page data from the file, it works. When I manipulate the code to make the processor think the pyramid contains one more resolution (85x128) beyond the actual smallest (170x256), I get the error you're seeing.

**Comment by mbklein** [comment]
Ah, never mind. I think I've got it.
