### ISSUE TITLE
Error: extract_area: parameter width not set

### ISSUE THREAD

**Issue by fitnycdigitalinitiatives** [samvera/serverless-iiif#155]
Hello,

Another error that I've seen in my lambda logs: `Error: extract_area: parameter width not set`. Includes the additional details: `
(process:8): GLib-GObject-CRITICAL **: 11:53:19.199: value "0" of type 'gint' is invalid or out of range for property 'width' of type 'gint'`.

Similarly to my last issue, this is only affecting some of the requests for the image. This one is for a specific region: `https://d2zekfy08kmwea.cloudfront.net/iiif/3/packages/2b35/be7a/d48b/4e01/974f/03d8/5806/12f6/ex_2023_0006-1fe49ba5-4b2d-49d9-b343-441d0b1e8ba9/objects/ef419813-759f-45b4-89ba-b9acec75aaf2-20230803_2-_CAS5899/8192,0,7,5466/1,342/0/default.jpg`

Lemme know the best way to send you the source file if that's helpful.

Thanks,

Joe

**Comment by mbklein** [comment]
The source file would be very helpful. My github username at gmail.

**Comment by fitnycdigitalinitiatives** [comment]
Great, just sent them over.

**Comment by mbklein** [comment]
I located the rounding error responsible for this one and submitted a fix. I should have an update available in the Serverless App Repository within a few days. I want to make sure any necessary fix for #154 gets deployed at the same time, but that one is proving a little trickier to reproduce.
