### ISSUE TITLE
Image API 3.0?

### ISSUE THREAD

**Issue by fitnycdigitalinitiatives** [samvera/serverless-iiif#34]
Hello,

Just came across this and am excited to test it out, but was wondering if there are any plans to upgrade this to IIIF Image API 3.0 in the near future?

**Comment by mbklein** [comment]
@fitnycdigitalinitiatives There's currently an [upstream dependency PR](https://github.com/samvera/node-iiif/pull/29) that would implement Image API v3.0, which would follow along here shortly after merge/release.

**Comment by fitnycdigitalinitiatives** [comment]
Excellent!
