### ISSUE TITLE
Question: can the IIIF image server simply return files that are not images

### ISSUE THREAD

**Issue by ryantomaselli** [samvera/serverless-iiif#82]
Hey guys;

If I wanted to have the IIIF server simply return files that aren't images (for example an mp4 file)...is there a recommended approach?

**Comment by mbklein** [comment]
If you use the CloudFront-enabled flavor, you can add additional origins and behaviors to the distribution it creates. I’ll have to give some thought to the best way to do that within the framework of a SAM deployment/CloudFormation stack, but you can play with the concept by making manual changes to the CloudFront distribution in the AWS console.

**Comment by fitnycdigitalinitiatives** [comment]
We have all our images commingled on the same bucket with resources of all media types, and only in cases where our digital repository identifies the file as an images does it access it specifically through the IIIF server—everything else (videos, audio, pdf) is just accessed directly through the s3 endpoint with a presigned URL. Curious, is there a value you're trying to gain by also having non-images pass through the IIIF server or is it more a convenience thing?

**Comment by ryantomaselli** [comment]
> If you use the CloudFront-enabled flavor, you can add additional origins and behaviors to the distribution it creates. I’ll have to give some thought to the best way to do that within the framework of a SAM deployment/CloudFormation stack, but you can play with the concept by making manual changes to the CloudFront distribution in the AWS console.

Thanks @mbklein! I'll do some tinkering...that is a good pointer.
