### ISSUE TITLE
Custom Domain Question

### ISSUE THREAD

**Issue by rsnyder** [samvera/serverless-iiif#89]
I'm setting the `CacheDomainName` parameter when deploying the CloudFront-Enabled version of 4.1.1.  DNS CNAME records are set to the same custom domain.  This all works as expected.  The service can be invoked with the custom domain the data in the info.json responses look great, with the exception of the `@id` field which includes the lambda domain rather than my custom domain.  I had expected that to be replaced with the value entered for CacheDomainName.  Is it possible to configure the service to include the custom domain in `@id` field?

**Comment by mbklein** [comment]
Thank you for reporting this. I think this has come up before, but I can't remember exactly how it played out. We're using a cloudfront-enabled instance and the `@id`s are looking like they should, so I think there must be some kind of configuration glitch. (It's not necessarily on your end – we use a customized deploy script and may have done something somewhere alone the line that the SAR click-to-deploy version doesn't.) Can you give me some details about your configuration and what you're seeing?

**Comment by rsnyder** [comment]
Thanks for the quick reply.  What would be helpful to know about my setup?  

I'm using the CloudFront-Enabled deploy script from an unmodified version of serverless-iiif repo that I forked earlier today.  I'm just setting 2 parameters, the CacheDomainName and the SourceBucket.  For the CacheDomainName I'm setting the value to `iiif-image.juncture-digital.org`.  

After the deploy completed I updated the CloudFront distribution config with the same custom domain name (using the `Alternate domain name (CNAME)`) field and pointed to the associated custom SSL certificate.  I'm using the Google Domains for DNS hosting, so I also needed to add the generated CloudFront ID to a CNAME record there.

**Comment by mbklein** [comment]
@rsnyder I think I understand now. Open up the lambda function in the AWS console and check its environment variables (under the `Configuration` tab). There should be a `forceHost` variable set to the custom domain that you want your IDs to use. This is usually set during deploy, but if you updated the CloudFront distribution's CNAME after the fact, that wouldn't have happened.

**Comment by rsnyder** [comment]
Thanks for this update.  After looking at the code (and some trial-and-error) that is what I arrived at too.  Thanks for confirming this was the correct resolution.  And, thanks for developing/supporting this great package.  It really simplifies the deployment of an IIIF image service.

Ron

From: Michael B. Klein ***@***.***>
Date: Tuesday, December 13, 2022 at 2:49 PM
To: samvera/serverless-iiif ***@***.***>
Cc: Ronald Snyder ***@***.***>, Mention ***@***.***>
Subject: Re: [samvera/serverless-iiif] Custom Domain Question (Issue #89)
Caution: This message did not originate from within ITHAKA's email system. Please use caution when opening attachments and following links within this message.

@rsnyder<https://github.com/rsnyder> I think I understand now. Open up the lambda function in the AWS console and check its environment variables (under the Configuration tab). There should be a forceHost variable set to the custom domain that you want your IDs to use. This is usually set during deploy, but if you updated the CloudFront distribution's CNAME after the fact, that wouldn't have happened.
