### ISSUE TITLE
Question - Apache Rewrite Parity w/ Serverless

### ISSUE THREAD

**Issue by codeclout** [samvera/serverless-iiif#92]
Hello, 

We have a Loris implementation of IIIF running Apache with rewrite rules to handle routing from a custom path structure to the IIIF API. Is there a way to mimic this functionality that is built into any of the dependencies in this project... or a solution from the broader community that has addressed this issue? 

e.g. `...mydomain.com/<iiif-image-id>/<params> -> ...mydomain.com/iiif/2/<iiif-image-id>/<params>`

Thank You,
Brian

**Comment by mbklein** [comment]
You could do this with a [CloudFront viewer-request](https://github.com/samvera/serverless-iiif#advanced-usage) function. Not using the Apache syntax, but with some pretty simple coding.
