### ISSUE TITLE
Question - Cloudfront Template Cache Bucket

### ISSUE THREAD

**Issue by codeclout** [samvera/serverless-iiif#95]
Hi, 

Thank you for all of your help in the past.

We were reviewing the CloudFront version of the template and noticed it creates a cache bucket. Is there a way to supply a cache bucket via the SAM cli or some other mechanism in order to bypass that functionality... similar to the how the Standalone version of the template works?

Thanks in Advance,
Brian

**Comment by mbklein** [comment]
A good deal of the reason the CloudFront version of the template exists is to support the workaround for response payloads larger than 6MB. (In fact, the only reason the parameter _exists_ in the standalone version is to support acting as the backend function for the CloudFront version.) So I didn't provide an option to toggle it off. Is there a reason you don't want to create the bucket? Nothing gets written to it unless it's larger than 6MB, and even those files are automatically lifecycle out after a day, so it's unlikely to rack up more than pennies per month in charges, if that much. (If you never produce a result larger than 6MB, the charge is $0 – there's no charge for an empty bucket just existing.)

**Comment by mbklein** [comment]
Ah, that's a little trickier. You'd have to modify the templates. Do you deploy directly from SAR, or using the `sam deploy` command?

**Comment by codeclout** [comment]
Hi @mbklein, 

We are currently using the SAM CLI `sam deploy`.

**Comment by mbklein** [comment]
Ah, that's way easier then. You just need to modify `sam/cloudfront/template.yml` in the following ways:

1. Remove the `CacheBucket` and `CacheBucketPolicy` blocks from the `Resources` section
2. Copy the `CacheBucket` block from the `Parameters` section of the standalone template to the cloudfront template.
3. Provide the name of your pre-existing cache bucket as the `CacheBucket` parameter to `sam deploy` (either on the command line or by adding it to the `ParameterOverrides` line of your `samconfig.toml`).

It'll be up to you to ensure that your bespoke bucket allows `GetObject` from the CloudFront Access Identity created by the template. The template can't create that policy for you. The [`CacheBucketPolicy`](https://github.com/samvera/serverless-iiif/blob/main/sam/cloudfront/template.yml#L179-L193) resource block might be able to help guide you what the bucket policy needs to look like.

**Comment by codeclout** [comment]
@mbklein - thank you... works as advertised
