### ISSUE TITLE
Question - v3 Layer

### ISSUE THREAD

**Issue by codeclout** [samvera/serverless-iiif#99]
Hi, 

We recently deployed a vanilla serverless-iiif with version 3 of the layer, but have been unsuccessful in being able to render an image. All of the defaults are in place. I added a couple of `tif` formatted images to the `tiffBucket` from Wikipedia (Creative Commons License). 

What we have observed:
- Requests for the images added to the `tiffBucket` result in the following error: `Error: Unhandled transformation error: null`
- Requests for `info.json` result in the following error: `Not Found`

Our observations are consistent whether we are testing via the CloudFront URL or the function URL. This is happening irrespective of the metadata being set on the image. 

Is there something we are missing outside of ensuring the images are in the correct bucket and are `tif` for a vanilla deployment?

**Comment by mbklein** [comment]
Thanks for the report. I'll take a look at it as soon as I can, but it might be a couple days. In the meantime, if you're deploying via `sam deploy` (and not from SAR), can you try running `npm update iiif-processor` in each of the root, `src`, and `dependencies` directories and redeploy? I just noticed that the current lock files are two point releases behind `iiif-processor`, and the latest version gets rid of the `Unhandled transformation error` catch-all in favor of what is hopefully a more meaningful error message.

**Comment by codeclout** [comment]
Hi @mbklein 

Thank you. Yes we are using `sam deploy` and we have been successful with your solution. 

Thanks Again,
Brian
